[application]

[web.app]

# HTML title tag content
title = "RPG Tools"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/main.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
icon = ["assets/monster.png"]
identifier = "com.netDReams"
publisher = "netDreams"
resources = ["assets/cthulhuhack.db"]
